# 开发环境和生产环境的配置文件
# 默认激活dev配置
spring:
  profiles:
    active: "dev"
---
# dev对应application-dev.yml 文件
spring:
  config:
    activate:
      on-profile: "dev"
---
# prod对应application-prod.yml 文件
spring:
  config:
    activate:
      on-profile: "prod"
---
#thymeleaf配置
spring:
  thymeleaf:
    #是否开启缓存，开发时可设置为false，默认为true
    cache: true
    #是否检查模板是否存在，默认为true
    check-template: true
    #是否检查模板位置是否存在，默认为true
    check-template-location: true
    #模板文件编码
    encoding: "UTF-8"
    #模板文件位置
    prefix: "classpath:/templates/"
    #Content-Type配置
    servlet: "content-type=text/html"
    #模板文件后缀
    suffix: "html"